export interface PhraseCategory {
  key: string;
  icon: string; // Lucide icon name
}

export interface Phrase {
  key: string;
  translations: Record<string, string>;
}

export const LANGUAGES = [
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
] as const;

export const CATEGORIES: PhraseCategory[] = [
  { key: 'medical', icon: 'heart-pulse' },
  { key: 'disaster', icon: 'alert-triangle' },
  { key: 'location', icon: 'map-pin' },
  { key: 'transport', icon: 'car' },
  { key: 'general', icon: 'message-circle' },
];

export const PHRASES: Record<string, Phrase[]> = {
  medical: [
    {
      key: 'need_ambulance',
      translations: {
        es: 'Necesito una ambulancia',
        en: 'I need an ambulance',
        fr: "J'ai besoin d'une ambulance",
        de: 'Ich brauche einen Krankenwagen',
        it: "Ho bisogno di un'ambulanza",
        pt: 'Preciso de uma ambulância',
        ar: 'أحتاج سيارة إسعاف',
        zh: '我需要救护车',
        ja: '救急車が必要です',
        ru: 'Мне нужна скорая помощь',
      },
    },
    {
      key: 'need_doctor',
      translations: {
        es: 'Necesito un médico',
        en: 'I need a doctor',
        fr: "J'ai besoin d'un médecin",
        de: 'Ich brauche einen Arzt',
        it: 'Ho bisogno di un medico',
        pt: 'Preciso de um médico',
        ar: 'أحتاج طبيب',
        zh: '我需要医生',
        ja: '医者が必要です',
        ru: 'Мне нужен врач',
      },
    },
    {
      key: 'allergic_to',
      translations: {
        es: 'Soy alérgico/a a...',
        en: 'I am allergic to...',
        fr: 'Je suis allergique à...',
        de: 'Ich bin allergisch gegen...',
        it: 'Sono allergico/a a...',
        pt: 'Sou alérgico/a a...',
        ar: '...لدي حساسية من',
        zh: '我对...过敏',
        ja: '...にアレルギーがあります',
        ru: 'У меня аллергия на...',
      },
    },
    {
      key: 'chest_pain',
      translations: {
        es: 'Tengo dolor en el pecho',
        en: 'I have chest pain',
        fr: "J'ai mal à la poitrine",
        de: 'Ich habe Brustschmerzen',
        it: 'Ho dolore al petto',
        pt: 'Tenho dor no peito',
        ar: 'لدي ألم في الصدر',
        zh: '我胸口疼',
        ja: '胸が痛いです',
        ru: 'У меня боль в груди',
      },
    },
    {
      key: 'cannot_breathe',
      translations: {
        es: 'No puedo respirar',
        en: 'I cannot breathe',
        fr: 'Je ne peux pas respirer',
        de: 'Ich kann nicht atmen',
        it: 'Non riesco a respirare',
        pt: 'Não consigo respirar',
        ar: 'لا أستطيع التنفس',
        zh: '我无法呼吸',
        ja: '息ができません',
        ru: 'Я не могу дышать',
      },
    },
  ],
  disaster: [
    {
      key: 'flood_warning',
      translations: {
        es: '¡Hay una inundación! Vaya a un lugar alto',
        en: 'There is a flood! Go to higher ground',
        fr: "Il y a une inondation ! Allez en hauteur",
        de: 'Es gibt eine Überschwemmung! Gehen Sie auf höheres Gelände',
        it: "C'è un'alluvione! Andate in alto",
        pt: 'Há uma inundação! Vá para um lugar alto',
        ar: 'هناك فيضان! اذهب إلى مكان مرتفع',
        zh: '发生洪水！请转移到高处',
        ja: '洪水です！高い場所に避難してください',
        ru: 'Наводнение! Поднимитесь на возвышенность',
      },
    },
    {
      key: 'where_shelter',
      translations: {
        es: '¿Dónde está el refugio más cercano?',
        en: 'Where is the nearest shelter?',
        fr: 'Où est le refuge le plus proche ?',
        de: 'Wo ist die nächste Unterkunft?',
        it: "Dov'è il rifugio più vicino?",
        pt: 'Onde fica o abrigo mais próximo?',
        ar: 'أين أقرب ملجأ؟',
        zh: '最近的避难所在哪里？',
        ja: '一番近い避難所はどこですか？',
        ru: 'Где ближайшее укрытие?',
      },
    },
    {
      key: 'people_trapped',
      translations: {
        es: 'Hay personas atrapadas',
        en: 'There are people trapped',
        fr: 'Il y a des personnes piégées',
        de: 'Es sind Menschen eingeschlossen',
        it: 'Ci sono persone intrappolate',
        pt: 'Há pessoas presas',
        ar: 'هناك أشخاص محاصرون',
        zh: '有人被困',
        ja: '人が閉じ込められています',
        ru: 'Люди заблокированы',
      },
    },
    {
      key: 'evacuation_route',
      translations: {
        es: '¿Cuál es la ruta de evacuación?',
        en: 'What is the evacuation route?',
        fr: "Quel est l'itinéraire d'évacuation ?",
        de: 'Was ist der Evakuierungsweg?',
        it: "Qual è il percorso di evacuazione?",
        pt: 'Qual é a rota de evacuação?',
        ar: 'ما هو طريق الإخلاء؟',
        zh: '疏散路线是什么？',
        ja: '避難ルートはどこですか？',
        ru: 'Какой маршрут эвакуации?',
      },
    },
  ],
  location: [
    {
      key: 'i_am_at',
      translations: {
        es: 'Estoy en...',
        en: 'I am at...',
        fr: 'Je suis à...',
        de: 'Ich bin bei...',
        it: 'Sono a...',
        pt: 'Estou em...',
        ar: '...أنا في',
        zh: '我在...',
        ja: '私は...にいます',
        ru: 'Я нахожусь в...',
      },
    },
    {
      key: 'i_am_lost',
      translations: {
        es: 'Estoy perdido/a',
        en: 'I am lost',
        fr: 'Je suis perdu(e)',
        de: 'Ich habe mich verirrt',
        it: 'Mi sono perso/a',
        pt: 'Estou perdido/a',
        ar: 'أنا ضائع',
        zh: '我迷路了',
        ja: '道に迷いました',
        ru: 'Я заблудился',
      },
    },
    {
      key: 'nearest_hospital',
      translations: {
        es: '¿Dónde está el hospital más cercano?',
        en: 'Where is the nearest hospital?',
        fr: "Où est l'hôpital le plus proche ?",
        de: 'Wo ist das nächste Krankenhaus?',
        it: "Dov'è l'ospedale più vicino?",
        pt: 'Onde fica o hospital mais próximo?',
        ar: 'أين أقرب مستشفى؟',
        zh: '最近的医院在哪里？',
        ja: '一番近い病院はどこですか？',
        ru: 'Где ближайшая больница?',
      },
    },
  ],
  transport: [
    {
      key: 'road_blocked',
      translations: {
        es: 'La carretera está cortada',
        en: 'The road is blocked',
        fr: 'La route est coupée',
        de: 'Die Straße ist gesperrt',
        it: 'La strada è bloccata',
        pt: 'A estrada está bloqueada',
        ar: 'الطريق مسدود',
        zh: '道路被封锁了',
        ja: '道路が封鎖されています',
        ru: 'Дорога перекрыта',
      },
    },
    {
      key: 'need_transport',
      translations: {
        es: 'Necesito transporte para evacuar',
        en: 'I need transport to evacuate',
        fr: "J'ai besoin d'un transport pour évacuer",
        de: 'Ich brauche Transport zur Evakuierung',
        it: 'Ho bisogno di un trasporto per evacuare',
        pt: 'Preciso de transporte para evacuar',
        ar: 'أحتاج وسيلة نقل للإخلاء',
        zh: '我需要交通工具撤离',
        ja: '避難のための交通手段が必要です',
        ru: 'Мне нужен транспорт для эвакуации',
      },
    },
  ],
  general: [
    {
      key: 'call_112',
      translations: {
        es: 'Llame al 112',
        en: 'Call 112',
        fr: 'Appelez le 112',
        de: 'Rufen Sie 112 an',
        it: 'Chiami il 112',
        pt: 'Ligue 112',
        ar: '112 اتصل بـ',
        zh: '请拨打112',
        ja: '112に電話してください',
        ru: 'Позвоните 112',
      },
    },
    {
      key: 'help',
      translations: {
        es: '¡Ayuda!',
        en: 'Help!',
        fr: 'Au secours !',
        de: 'Hilfe!',
        it: 'Aiuto!',
        pt: 'Socorro!',
        ar: '!النجدة',
        zh: '救命！',
        ja: '助けて！',
        ru: 'Помогите!',
      },
    },
    {
      key: 'do_you_speak',
      translations: {
        es: '¿Habla inglés?',
        en: 'Do you speak English?',
        fr: 'Parlez-vous anglais ?',
        de: 'Sprechen Sie Englisch?',
        it: 'Parla inglese?',
        pt: 'Fala inglês?',
        ar: 'هل تتحدث الإنجليزية؟',
        zh: '你会说英语吗？',
        ja: '英語を話しますか？',
        ru: 'Вы говорите по-английски?',
      },
    },
    {
      key: 'thank_you',
      translations: {
        es: 'Gracias',
        en: 'Thank you',
        fr: 'Merci',
        de: 'Danke',
        it: 'Grazie',
        pt: 'Obrigado/a',
        ar: 'شكرا',
        zh: '谢谢',
        ja: 'ありがとう',
        ru: 'Спасибо',
      },
    },
  ],
};

/** Map language codes to BCP-47 tags for Web Speech API */
export const SPEECH_LANG_MAP: Record<string, string> = {
  es: 'es-ES',
  en: 'en-GB',
  fr: 'fr-FR',
  de: 'de-DE',
  it: 'it-IT',
  pt: 'pt-PT',
  ar: 'ar-SA',
  zh: 'zh-CN',
  ja: 'ja-JP',
  ru: 'ru-RU',
};
