"""Mock AEMET CAP alert data for demo mode."""
from datetime import datetime, timedelta, timezone


def get_mock_aemet_alerts() -> list[dict]:
    """Return AEMET-format alerts matching the DANA scenario."""
    now = datetime.now(timezone.utc)
    return [
        {
            "identifier": "AEMET-2026032900001",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=6)).isoformat(),
            "severity": "red",
            "event": "Lluvia",
            "headline": "Aviso rojo por lluvias - Valencia y Alicante",
            "description": "Se esperan precipitaciones acumuladas de 200-400 mm en 12 horas. Riesgo extremo de inundaciones subitas. Afecta a las provincias de Valencia y Alicante.",
            "area_desc": "Valencia, Alicante",
            "geocode": "46",
            "onset": (now - timedelta(hours=6)).isoformat(),
            "expires": (now + timedelta(hours=12)).isoformat(),
        },
        {
            "identifier": "AEMET-2026032900002",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=5)).isoformat(),
            "severity": "red",
            "event": "Viento",
            "headline": "Aviso rojo por viento - Litoral valenciano",
            "description": "Rachas de viento del este de 100-130 km/h en zonas costeras. Peligro extremo. Mantenerse alejado de la costa.",
            "area_desc": "Valencia, Castellon",
            "geocode": "46",
            "onset": (now - timedelta(hours=5)).isoformat(),
            "expires": (now + timedelta(hours=10)).isoformat(),
        },
        {
            "identifier": "AEMET-2026032900003",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=4)).isoformat(),
            "severity": "orange",
            "event": "Lluvia",
            "headline": "Aviso naranja por lluvias - Castellon y Albacete",
            "description": "Se esperan precipitaciones acumuladas de 80-150 mm en 12 horas. Riesgo importante de inundaciones y desbordamientos.",
            "area_desc": "Castellon, Albacete",
            "geocode": "12",
            "onset": (now - timedelta(hours=4)).isoformat(),
            "expires": (now + timedelta(hours=18)).isoformat(),
        },
        {
            "identifier": "AEMET-2026032900004",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=3)).isoformat(),
            "severity": "orange",
            "event": "Lluvia",
            "headline": "Aviso naranja por lluvias - Murcia",
            "description": "Precipitaciones de 60-100 mm en 12 horas con tormentas localmente fuertes. Precaucion en ramblas y zonas bajas.",
            "area_desc": "Murcia",
            "geocode": "30",
            "onset": (now - timedelta(hours=3)).isoformat(),
            "expires": (now + timedelta(hours=20)).isoformat(),
        },
        {
            "identifier": "AEMET-2026032900005",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=2)).isoformat(),
            "severity": "yellow",
            "event": "Costero",
            "headline": "Aviso amarillo fenomeno costero - Litoral mediterraneo",
            "description": "Oleaje de 4-5 metros en litoral de Valencia, Alicante y Murcia. Peligro para navegacion y actividades costeras.",
            "area_desc": "Litoral de Valencia, Alicante y Murcia",
            "geocode": "46",
            "onset": (now - timedelta(hours=8)).isoformat(),
            "expires": (now + timedelta(hours=24)).isoformat(),
        },
        {
            "identifier": "AEMET-2026032900006",
            "sender": "AEMET",
            "sent": (now - timedelta(hours=1)).isoformat(),
            "severity": "yellow",
            "event": "Tormentas",
            "headline": "Aviso amarillo tormentas - Interior peninsular este",
            "description": "Posibles tormentas con granizo y rachas de viento de 70 km/h en Cuenca, Teruel y este de Guadalajara.",
            "area_desc": "Cuenca, Teruel, Guadalajara",
            "geocode": "16",
            "onset": (now - timedelta(hours=1)).isoformat(),
            "expires": (now + timedelta(hours=15)).isoformat(),
        },
    ]
