"""add preparedness emergency plan and alert intelligence tables

Revision ID: 13ec9d1cfb62
Revises: ca6a7bcfdd4e
Create Date: 2026-03-22 19:56:03.529683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ec9d1cfb62'
down_revision: Union[str, None] = 'ca6a7bcfdd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('batched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_user_id'), 'alert_deliveries', ['user_id'], unique=False)
    op.create_table('alert_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('emergency_override', sa.Boolean(), nullable=False),
    sa.Column('batch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('snoozed_hazards', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=True)
    op.create_table('emergency_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_members', sa.JSON(), nullable=False),
    sa.Column('meeting_points', sa.JSON(), nullable=False),
    sa.Column('communication_plan', sa.JSON(), nullable=False),
    sa.Column('evacuation_notes', sa.String(length=2000), nullable=True),
    sa.Column('insurance_info', sa.JSON(), nullable=True),
    sa.Column('pet_info', sa.JSON(), nullable=True),
    sa.Column('important_documents', sa.JSON(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_plans_user_id'), 'emergency_plans', ['user_id'], unique=True)
    op.create_table('preparedness_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('item_key', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparedness_items_user_id'), 'preparedness_items', ['user_id'], unique=False)
    op.create_table('preparedness_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('kit_score', sa.Float(), nullable=False),
    sa.Column('plan_score', sa.Float(), nullable=False),
    sa.Column('alerts_score', sa.Float(), nullable=False),
    sa.Column('community_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparedness_snapshots_user_id'), 'preparedness_snapshots', ['user_id'], unique=False)
    op.add_column('users', sa.Column('preparedness_score', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preparedness_score')
    op.drop_index(op.f('ix_preparedness_snapshots_user_id'), table_name='preparedness_snapshots')
    op.drop_table('preparedness_snapshots')
    op.drop_index(op.f('ix_preparedness_items_user_id'), table_name='preparedness_items')
    op.drop_table('preparedness_items')
    op.drop_index(op.f('ix_emergency_plans_user_id'), table_name='emergency_plans')
    op.drop_table('emergency_plans')
    op.drop_index(op.f('ix_alert_preferences_user_id'), table_name='alert_preferences')
    op.drop_table('alert_preferences')
    op.drop_index(op.f('ix_alert_deliveries_user_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    # ### end Alembic commands ###
