"""add sms_subscriptions table

Revision ID: 4022f8178e27
Revises: 5de10cab8475
Create Date: 2026-03-21 19:16:26.553928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4022f8178e27'
down_revision: Union[str, None] = '5de10cab8475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_subscriptions_phone_number'), 'sms_subscriptions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_sms_subscriptions_province_code'), 'sms_subscriptions', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_subscriptions_province_code'), table_name='sms_subscriptions')
    op.drop_index(op.f('ix_sms_subscriptions_phone_number'), table_name='sms_subscriptions')
    op.drop_table('sms_subscriptions')
    # ### end Alembic commands ###
