"""add risk_forecasts table

Revision ID: 5de10cab8475
Revises: 30bbbe6a8de3
Create Date: 2026-03-20 22:11:22.015134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de10cab8475'
down_revision: Union[str, None] = '30bbbe6a8de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('hazard', sa.String(length=20), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('q10', sa.Float(), nullable=False),
    sa.Column('q50', sa.Float(), nullable=False),
    sa.Column('q90', sa.Float(), nullable=False),
    sa.Column('attention_weights', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_forecasts_province_code'), 'risk_forecasts', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_forecasts_province_code'), table_name='risk_forecasts')
    op.drop_table('risk_forecasts')
    # ### end Alembic commands ###
