"""add seismic coldwave windstorm scores

Revision ID: 80678029a7c0
Revises: f72bea6738d4
Create Date: 2026-03-19 20:39:45.732354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80678029a7c0'
down_revision: Union[str, None] = 'f72bea6738d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provinces', sa.Column('seismic_risk_weight', sa.Float(), server_default='0.3', nullable=False))
    op.add_column('provinces', sa.Column('coldwave_risk_weight', sa.Float(), server_default='0.3', nullable=False))
    op.add_column('provinces', sa.Column('windstorm_risk_weight', sa.Float(), server_default='0.3', nullable=False))
    op.add_column('risk_scores', sa.Column('seismic_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('risk_scores', sa.Column('coldwave_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('risk_scores', sa.Column('windstorm_score', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'windstorm_score')
    op.drop_column('risk_scores', 'coldwave_score')
    op.drop_column('risk_scores', 'seismic_score')
    op.drop_column('provinces', 'windstorm_risk_weight')
    op.drop_column('provinces', 'coldwave_risk_weight')
    op.drop_column('provinces', 'seismic_risk_weight')
    # ### end Alembic commands ###
