"""expand_user_model_auth_and_profile

Revision ID: ca6a7bcfdd4e
Revises: 4022f8178e27
Create Date: 2026-03-21 22:45:54.852909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6a7bcfdd4e'
down_revision: Union[str, None] = '4022f8178e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
