"""add safety check tables

Revision ID: cb76d942f4bc
Revises: 13ec9d1cfb62
Create Date: 2026-03-22 21:39:45.192367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb76d942f4bc'
down_revision: Union[str, None] = '13ec9d1cfb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('linked_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'linked_user_id', name='uq_family_link')
    )
    op.create_index(op.f('ix_family_links_linked_user_id'), 'family_links', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_family_links_user_id'), 'family_links', ['user_id'], unique=False)
    op.create_table('safety_check_ins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_check_ins_province_code'), 'safety_check_ins', ['province_code'], unique=False)
    op.create_index(op.f('ix_safety_check_ins_user_id'), 'safety_check_ins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_check_ins_user_id'), table_name='safety_check_ins')
    op.drop_index(op.f('ix_safety_check_ins_province_code'), table_name='safety_check_ins')
    op.drop_table('safety_check_ins')
    op.drop_index(op.f('ix_family_links_user_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_linked_user_id'), table_name='family_links')
    op.drop_table('family_links')
    # ### end Alembic commands ###
