"""add_weather_daily_summary

Revision ID: f72bea6738d4
Revises: c4ed565373d5
Create Date: 2026-03-19 12:01:09.142216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72bea6738d4'
down_revision: Union[str, None] = 'c4ed565373d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_daily_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=False),
    sa.Column('temperature_avg', sa.Float(), nullable=False),
    sa.Column('humidity_avg', sa.Float(), nullable=False),
    sa.Column('humidity_min', sa.Float(), nullable=False),
    sa.Column('precipitation_sum', sa.Float(), nullable=False),
    sa.Column('wind_speed_max', sa.Float(), nullable=False),
    sa.Column('wind_speed_avg', sa.Float(), nullable=False),
    sa.Column('wind_gusts_max', sa.Float(), nullable=True),
    sa.Column('pressure_avg', sa.Float(), nullable=True),
    sa.Column('soil_moisture_avg', sa.Float(), nullable=True),
    sa.Column('uv_index_max', sa.Float(), nullable=True),
    sa.Column('cloud_cover_avg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_code', 'date', name='uq_province_date')
    )
    op.create_index('ix_daily_summary_province_date', 'weather_daily_summary', ['province_code', 'date'], unique=False)
    op.create_index(op.f('ix_weather_daily_summary_date'), 'weather_daily_summary', ['date'], unique=False)
    op.create_index(op.f('ix_weather_daily_summary_province_code'), 'weather_daily_summary', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_daily_summary_province_code'), table_name='weather_daily_summary')
    op.drop_index(op.f('ix_weather_daily_summary_date'), table_name='weather_daily_summary')
    op.drop_index('ix_daily_summary_province_date', table_name='weather_daily_summary')
    op.drop_table('weather_daily_summary')
    # ### end Alembic commands ###
